'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class HTML
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FoundationLibrary.HTML", GetType(HTML).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;a&gt;...&lt;/a&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;a&gt; ορίζει έναν υπερσύνδεσμο, ο οποίος χρησιμοποιείται για τη σύνδεση από τη μια σελίδα στην άλλη.
        '''	Το πιο σημαντικό χαρακτηριστικό του στοιχείου &lt;a&gt; είναι το χαρακτηριστικό href, 
        '''	το οποίο υποδεικνύει τον προορισμό του συνδέσμου.
        '''
        '''	Από προεπιλογή, οι σύνδεσμοι θα εμφανίζονται ως εξής σε όλα τα προγράμματα περιήγησης: 
        '''
        '''	*Ένας σύνδεσμος χωρίς επίσκεψη είναι υπογραμμισμένος και μπλε.
        '''	*Ένας σύνδεσμος που επισκεφτήκατε είναι υπογραμμισμένος και μωβ. 
        '''	* [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property a() As String
            Get
                Return ResourceManager.GetString("a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;abbr title=&quot;...&quot;&gt;....&lt;/abbr&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;abbr&gt; ορίζει μια συντομογραφία ή ένα ακρωνύμιο
        '''	Συμβουλή: Χρησιμοποιήστε το χαρακτηριστικό καθολικού τίτλου για να
        '''	εμφανίσετε την περιγραφή για τη συντομογραφία/ακρωνύμιο όταν 
        '''	τοποθετείτε το ποντίκι πάνω από το στοιχείο.
        '''	
        '''	*Λειτουργεί μόνο μαζι με την ιδιότητα Title
        '''
        '''Παράδειγμα:
        '''	&lt;abbr title=&quot;Cascading Style Sheets&quot;&gt;CSS&lt;/abbr&gt;
        '''					.
        '''</summary>
        Friend Shared ReadOnly Property abbr() As String
            Get
                Return ResourceManager.GetString("abbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;address&gt;
        '''	......
        '''	......
        '''	......
        '''	&lt;/address&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;address&gt; ορίζει τα στοιχεία επικοινωνίας για τον συγγραφέα/κάτοχο ενός εγγράφου ή ενός άρθρου. 
        '''	Τα στοιχεία επικοινωνίας μπορεί να είναι μια διεύθυνση email, διεύθυνση URL, 
        '''	φυσική διεύθυνση, αριθμός τηλεφώνου, λαβή μέσων κοινωνικής δικτύωσης κ.λπ. 
        '''
        '''	Το κείμενο στο στοιχείο &lt;address&gt; συνήθως αποδίδεται με πλάγια γραφή και τα προγράμματα περιήγησης 
        '''
        '''	θα προσθέτουν πάντα μια αλλαγή γραμμής πριν και μετά το στοιχε [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property address() As String
            Get
                Return ResourceManager.GetString("address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Επεξήγηση:
        '''	Η ετικέτα &lt;area&gt; ορίζει μια περιοχή μέσα σε έναν 
        '''	χάρτη εικόνας (ένας χάρτης εικόνας είναι μια εικόνα με περιοχές με δυνατότητα κλικ).
        '''
        '''	Τα στοιχεία &lt;area&gt; είναι πάντα ένθετα μέσα σε μια ετικέτα &lt;map&gt;.
        '''
        '''	Σημείωση: Το χαρακτηριστικό usemap στο &lt;img&gt; σχετίζεται με το χαρακτηριστικό
        '''	name του στοιχείου &lt;map&gt; και δημιουργεί μια σχέση μεταξύ της εικόνας και του χάρτη.
        '''Παράδειγμα:
        '''	&lt;img src=&quot;workplace.jpg&quot; alt=&quot;Workplace&quot; usemap=&quot;#workmap&quot; width=&quot;400&quot; height=&quot;379&quot;&gt;
        '''
        '''	&lt;map name=&quot;workmap&quot;&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property area() As String
            Get
                Return ResourceManager.GetString("area", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	 &lt;article&gt;
        '''	 .....
        '''	 .....
        '''	 .....
        '''	 &lt;/article&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;article&gt; καθορίζει ανεξάρτητο, αυτόνομο περιεχόμενο.
        '''	Ένα άρθρο θα πρέπει να έχει νόημα από μόνο του και θα πρέπει να είναι 
        '''	δυνατή η διανομή του ανεξάρτητα από τον υπόλοιπο ιστότοπο. 
        '''
        '''	Πιθανές πηγές για το στοιχείο &lt;article&gt;: 
        '''	-Ανάρτηση φόρουμ 
        '''	-Ανάρτηση ιστολογίου 
        '''	-Ειδήσεις
        '''
        '''	*το στοιχείο &lt;article&gt; δεν αποδίδεται ως κάτι ιδιαίτερο σε ένα πρόγραμμα περιήγησης.
        '''	Ωστόσο, μπορείτε να χρησιμοποιήσετε το CS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property article() As String
            Get
                Return ResourceManager.GetString("article", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;aside&gt;
        '''	....
        '''	....
        '''	....
        '''	&lt;/aside&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;aside&gt; ορίζει κάποιο περιεχόμενο εκτός από το περιεχόμενο στο οποίο τοποθετείται. 
        '''	Το παράπλευρο περιεχόμενο θα πρέπει να σχετίζεται έμμεσα με το περιβάλλον περιεχόμενο. 
        '''	
        '''	*Συμβουλή: Το περιεχόμενο &lt;aside&gt; τοποθετείται συχνά ως πλαϊνή γραμμή σε ένα έγγραφο. 
        '''
        '''	*Σημείωση: Το στοιχείο &lt;aside&gt; δεν αποδίδεται ως κάτι ιδιαίτερο σε ένα πρόγραμμα περιήγησης. 
        '''	Ωστόσο, μπορείτε να χρησιμοποιήσετε το CSS για το στυλ του στοιχείου  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property aside() As String
            Get
                Return ResourceManager.GetString("aside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;audio controls&gt;
        '''		..........
        '''		..........
        '''		..........
        '''	&lt;/audio&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;audio&gt; χρησιμοποιείται για την ενσωμάτωση περιεχομένου ήχου σε ένα έγγραφο, 
        '''	όπως μουσική ή άλλες ροές ήχου. Η ετικέτα &lt;audio&gt; περιέχει μία ή 
        '''	περισσότερες ετικέτες &lt;source&gt; με διαφορετικές πηγές ήχου.
        '''
        '''	Το πρόγραμμα περιήγησης θα επιλέξει την πρώτη πηγή που υποστηρίζει.
        '''	Το κείμενο μεταξύ των ετικετών &lt;audio&gt; και &lt;/audio&gt; 
        '''	θα εμφανίζεται μόνο σε προγράμματα περιήγησης που δεν υποστηρίζουν το [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property audio() As String
            Get
                Return ResourceManager.GetString("audio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;b&gt;....&lt;/b&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;b&gt; καθορίζει το έντονο κείμενο χωρίς καμία επιπλέον σημασία.
        '''	
        '''	*Σημείωση: Σύμφωνα με την προδιαγραφή HTML5,
        '''	η ετικέτα &lt;b&gt; θα πρέπει να χρησιμοποιείται ως ΤΕΛΕΥΤΑΙΑ λύση
        '''	όταν καμία άλλη ετικέτα δεν είναι πιο κατάλληλη.
        '''	
        '''	-Η προδιαγραφή δηλώνει ότι οι επικεφαλίδες πρέπει να υποδηλώνονται με τις ετικέτες &lt;h1&gt; έως &lt;h6&gt;, 
        '''	-το κείμενο που τονίζεται πρέπει να συμβολίζεται με την ετικέτα &lt;em&gt;,
        '''	-το σημαντικό κείμενο πρέπει να συμβολίζεται με την ετικέτα [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property b() As String
            Get
                Return ResourceManager.GetString("b", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;head&gt;
        '''		&lt;base href=&quot;....&quot; target=&quot;....&quot;&gt;
        '''	&lt;/head&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;base&gt; καθορίζει τη βασική διεύθυνση URL και/ή τον στόχο για όλες τις σχετικές διευθύνσεις URL σε ένα έγγραφο. 
        '''	Η ετικέτα &lt;base&gt; πρέπει να έχει είτε ένα χαρακτηριστικό href ή ένα χαρακτηριστικό στόχο ή και τα δύο.
        '''	Μπορεί να υπάρχει μόνο ένα στοιχείο &lt;base&gt; σε ένα έγγραφο και πρέπει να βρίσκεται μέσα στο στοιχείο &lt;head&gt;.
        '''
        '''Παράδειγμα:
        '''	 &lt;head&gt;
        '''		&lt;base href=&quot;https://www.w3schools.com/&quot; target=&quot;_blank&quot;&gt;
        '''	 &lt;/head&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property base() As String
            Get
                Return ResourceManager.GetString("base", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	
        '''  &lt;bdi&gt;hrefs&lt;/bdi&gt;
        '''  &lt;bdi&gt;jdoe&lt;/bdi&gt;
        '''  &lt;bdi&gt;إيان&lt;/bdi&gt;
        '''
        '''
        '''Επεξήγηση:
        '''	Το BDI σημαίνει απομόνωση διπλής κατεύθυνσης. 
        '''
        '''	Η ετικέτα &lt;bdi&gt; απομονώνει ένα μέρος του κειμένου που μπορεί να μορφοποιηθεί σε διαφορετική κατεύθυνση 
        '''	από άλλο κείμενο εκτός αυτού.
        '''
        '''	Αυτό το στοιχείο είναι χρήσιμο κατά την ενσωμάτωση περιεχομένου που δημιουργείται από χρήστες με άγνωστη κατεύθυνση κειμένου.
        '''Παράδειγμα:
        '''	&lt;ul&gt;
        '''		&lt;li&gt;User &lt;bdi&gt;hrefs&lt;/bdi&gt;: 60 points&lt;/li&gt;
        '''		&lt;li&gt;User &lt;bdi&gt;jdoe&lt;/bdi&gt;: 80 points&lt;/li [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property bdi() As String
            Get
                Return ResourceManager.GetString("bdi", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;bdo dir=&quot;rtl&quot;&gt;......&lt;/bdo&gt;
        '''
        '''Επεξήγηση:
        '''	Το BDO σημαίνει παράκαμψη διπλής κατεύθυνσης. 
        '''	Η ετικέτα &lt;bdo&gt; χρησιμοποιείται για να παρακάμψει την τρέχουσα κατεύθυνση κειμένου.
        '''
        '''Παράδειγμα:
        '''	&lt;bdo dir=&quot;rtl&quot;&gt;
        '''		This text will go right-to-left.
        '''	&lt;/bdo&gt;
        '''
        '''.
        '''</summary>
        Friend Shared ReadOnly Property bdo() As String
            Get
                Return ResourceManager.GetString("bdo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;blockquote&gt;....&lt;/blockquote&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;blockquote&gt; καθορίζει μια ενότητα που αναφέρεται από άλλη πηγή.
        '''	Τα προγράμματα περιήγησης συνήθως δημιουργούν εσοχές &lt;blockquote&gt;
        '''
        '''	*Συμβουλή: Χρησιμοποιήστε το &lt;q&gt; για ενσωματωμένες (σύντομες) εισαγωγικές.
        '''
        '''Παράδειγμα:
        '''	&lt;blockquote cite=&quot;http://www.worldwildlife.org/who/index.html&quot;&gt;
        '''		For 50 years, WWF has been protecting the future of nature. 
        '''		The world&apos;s leading conservation organization, WWF works in 100 countries and is supp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property blockquote() As String
            Get
                Return ResourceManager.GetString("blockquote", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;body&gt;
        '''		....
        '''		....
        '''		....
        '''	&lt;/body&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;body&gt; ορίζει το σώμα του εγγράφου. 
        '''	Το στοιχείο &lt;body&gt; περιέχει όλα τα περιεχόμενα ενός εγγράφου HTML, όπως επικεφαλίδες, 
        '''	παραγράφους, εικόνες, υπερσυνδέσμους, πίνακες, λίστες κ.λπ.
        '''	
        '''	*Σημείωση: Μπορεί να υπάρχει μόνο ένα στοιχείο &lt;body&gt; σε ένα έγγραφο HTML.
        '''
        '''Παράδειγμα:
        '''	&lt;body&gt;
        '''		&lt;h1&gt;Hello world!&lt;/h1&gt;
        '''		&lt;p&gt;&lt;a href=&quot;https://www.w3schools.com&quot;&gt;Visit W3Schools.com!&lt;/a&gt;&lt;/p&gt;
        '''	&lt;/body&gt;.
        '''</summary>
        Friend Shared ReadOnly Property body() As String
            Get
                Return ResourceManager.GetString("body", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	.....&lt;br&gt;.....
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;br&gt; εισάγει μια αλλαγή γραμμής.
        '''	
        '''	Η ετικέτα &lt;br&gt; είναι χρήσιμη για τη σύνταξη διευθύνσεων ή ποιημάτων.
        '''	
        '''	Η ετικέτα &lt;br&gt; είναι μια κενή ετικέτα που σημαίνει ότι δεν έχει τερματική ετικέτα.
        '''	
        '''Παράδειγμα:
        '''	&lt;p&gt;To force&lt;br&gt; line breaks&lt;br&gt; in a text,&lt;br&gt; use the br&lt;br&gt; element.&lt;/p&gt;.
        '''</summary>
        Friend Shared ReadOnly Property br() As String
            Get
                Return ResourceManager.GetString("br", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;button&gt;....&lt;/button&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;button&gt; ορίζει ένα κουμπί με δυνατότητα κλικ. 
        '''
        '''	Μέσα σε ένα στοιχείο &lt;button&gt; μπορείτε να βάλετε κείμενο (και ετικέτες όπως &lt;i&gt;, &lt;b&gt;, &lt;strong&gt;, &lt;br&gt;, &lt;img&gt;, κ.λπ.). 
        '''	Αυτό δεν είναι δυνατό με ένα κουμπί που δημιουργήθηκε με το στοιχείο &lt;input&gt;!
        '''	
        '''	*Συμβουλή: Καθορίζετε πάντα το χαρακτηριστικό type για ένα στοιχείο &lt;button&gt;, 
        '''		για να ενημερώνετε τα προγράμματα περιήγησης για τον τύπο του κουμπιού. 
        '''	*Συμβουλή: Μπορείτε εύκολα να στυλ κουμπι [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property button() As String
            Get
                Return ResourceManager.GetString("button", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;canvas&gt;....&lt;/canvas&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;canvas&gt; χρησιμοποιείται για τη σχεδίαση γραφικών, εν κινήσει, μέσω scripting (συνήθως JavaScript).
        '''	
        '''	Η ετικέτα &lt;canvas&gt; είναι διαφανής και είναι μόνο ένα κοντέινερ για γραφικά,
        '''		πρέπει να χρησιμοποιήσετε ένα σενάριο για να σχεδιάσετε πραγματικά τα γραφικά.
        '''
        '''	Οποιοδήποτε κείμενο μέσα στο στοιχείο &lt;canvas&gt; θα εμφανίζεται σε προγράμματα περιήγησης με
        '''		απενεργοποιημένη JavaScript και σε προγράμματα περιήγησης που δεν υποστηρίζουν &lt;canvas&gt;.
        '''
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property canvas() As String
            Get
                Return ResourceManager.GetString("canvas", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;caption&gt;.....&lt;/caption&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;caption&gt; ορίζει μια λεζάντα πίνακα.
        '''	
        '''	Η ετικέτα &lt;caption&gt; πρέπει να εισαχθεί αμέσως μετά την ετικέτα &lt;table&gt;.
        '''	
        '''	*Συμβουλή: Από προεπιλογή, μια λεζάντα πίνακα θα είναι στοίχιση στο κέντρο πάνω από έναν πίνακα. 
        '''	Ωστόσο, οι ιδιότητες CSS, text-align και caption-side μπορούν να χρησιμοποιηθούν για τη στοίχιση
        '''	και την τοποθέτηση της λεζάντας.
        '''	
        '''
        '''Παράδειγμα:
        '''	&lt;table&gt;
        '''		&lt;caption&gt;Monthly savings&lt;/caption&gt;
        '''		&lt;tr&gt;
        '''			&lt;th&gt;Month&lt;/th&gt;
        '''			&lt;t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property caption() As String
            Get
                Return ResourceManager.GetString("caption", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;cite&gt;....&lt;/cite&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;cite&gt; ορίζει τον τίτλο ενός δημιουργικού έργου 
        '''	(π.χ. ένα βιβλίο, ένα ποίημα, ένα τραγούδι, μια ταινία, ένας πίνακας, ένα γλυπτό κ.λπ.).
        '''	
        '''	*Σημείωση: Το όνομα ενός ατόμου δεν είναι ο τίτλος ενός έργου.
        '''	
        '''	Το κείμενο στο στοιχείο &lt;cite&gt; συνήθως αποδίδεται με πλάγια γραφή.
        '''	
        '''Παράδειγμα:
        '''	&lt;cite&gt;The Scream&lt;/cite&gt;.
        '''</summary>
        Friend Shared ReadOnly Property cite() As String
            Get
                Return ResourceManager.GetString("cite", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;code&gt;....&lt;/code&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;code&gt; χρησιμοποιείται για να ορίσει ένα κομμάτι κώδικα υπολογιστή. 
        '''	Το περιεχόμενο στο εσωτερικό εμφανίζεται στην προεπιλεγμένη γραμματοσειρά monospace του προγράμματος περιήγησης.
        '''	
        '''	*Συμβουλή: Αυτή η ετικέτα δεν έχει καταργηθεί. 
        '''	Ωστόσο, είναι δυνατό να επιτευχθεί πιο πλούσιο αποτέλεσμα χρησιμοποιώντας CSS.
        '''
        '''Παράδειγμα:
        '''	&lt;code&gt;button&lt;/code&gt;.
        '''</summary>
        Friend Shared ReadOnly Property code() As String
            Get
                Return ResourceManager.GetString("code", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''    &lt;col&gt;....&lt;/col&gt;
        '''
        '''Επεξήγηση:
        '''	Η ετικέτα &lt;col&gt; καθορίζει τις ιδιότητες στήλης για κάθε στήλη μέσα σε ένα στοιχείο &lt;colgroup&gt;.
        '''
        '''	Η ετικέτα &lt;col&gt; είναι χρήσιμη για την εφαρμογή στυλ σε ολόκληρες στήλες, αντί να επαναλαμβάνει
        '''	τα στυλ για κάθε κελί, για κάθε σειρά.
        '''
        '''Παράδειγμα:
        '''	&lt;table&gt;
        '''        &lt;colgroup&gt;
        '''            &lt;col span=&quot;2&quot; style=&quot;background-color:red&quot;&gt;
        '''            &lt;col style=&quot;background-color:yellow&quot;&gt;
        '''        &lt;/colgroup&gt;
        '''    &lt;tr&gt;
        '''        &lt;th&gt;ISBN&lt;/th&gt;
        '''        &lt;th&gt;Title&lt;/th&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property col() As String
            Get
                Return ResourceManager.GetString("col", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ετικέτα:
        '''	&lt;!DOCTYPE html&gt;
        '''
        '''Επεξήγηση:
        '''	Η Ετικές &lt;!DOCTYPE html&gt; Είναι μια πληροφορία για την έκδοση  της HMTL
        '''	Μπαίνει στην αρχή του εγράφου
        '''Ιδιότητες:
        '''	Δεν πέρνει Ιδιότητες
        '''
        '''Παράδειγμα:
        '''	&lt;!DOCTYPE html&gt;
        '''					.
        '''</summary>
        Friend Shared ReadOnly Property doctype() As String
            Get
                Return ResourceManager.GetString("doctype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''accent-color	Specifies an accent color for user-interface controls
        '''align-content	Specifies the alignment between the lines inside a flexible container when the items do not use all available space
        '''align-items	Specifies the alignment for items inside a flexible container
        '''align-self	Specifies the alignment for selected items inside a flexible container
        '''all	Resets all properties (except unicode-bidi and direction)
        '''animation	A shorthand property for all the animation-* properties
        '''animation-delay	Specifi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property dokimastiko() As String
            Get
                Return ResourceManager.GetString("dokimastiko", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Τι είναι HTML ;
        '''-----------------
        '''
        '''Το HTML σημαίνει Hyper Text Markup Language. 
        '''
        '''-Η HTML είναι η τυπική γλώσσα σήμανσης για τη δημιουργία ιστοσελίδων
        '''-Η HTML περιγράφει τη δομή μιας ιστοσελίδας 
        '''-Η HTML αποτελείται από μια σειρά στοιχείων 
        '''-Τα στοιχεία HTML λένε στο πρόγραμμα περιήγησης πώς να εμφανίζει το περιεχόμενο 
        '''-Τα στοιχεία HTML επισημαίνουν κομμάτια περιεχομένου όπως &quot;αυτή είναι μια επικεφαλίδα&quot;, 
        '''&quot;αυτή είναι μια παράγραφος&quot;, &quot;αυτό είναι ένας σύνδεσμος&quot; κ.λπ.
        '''
        '''------------------------- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property HTMLmenu() As String
            Get
                Return ResourceManager.GetString("HTMLmenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Επεξήγηση:
        '''	Η ετικέτα σχολίου χρησιμοποιείται για την εισαγωγή σχολίων στον πηγαίο κώδικα. 
        '''
        '''	Τα σχόλια δεν εμφανίζονται στα προγράμματα περιήγησης. 
        '''	Μπορείτε να χρησιμοποιήσετε σχόλια για να εξηγήσετε τον κώδικά σας,
        '''	κάτι που μπορεί να σας βοηθήσει όταν επεξεργαστείτε τον πηγαίο κώδικα σε μεταγενέστερη ημερομηνία.
        '''
        '''	Αυτό είναι ιδιαίτερα χρήσιμο εάν έχετε πολύ κώδικα.
        '''
        '''Παράδειγμα:
        '''	&lt;!-- ειναι ενα εγρφαφο HTML --&gt;
        '''					
        '''
        '''.
        '''</summary>
        Friend Shared ReadOnly Property Σχολιο() As String
            Get
                Return ResourceManager.GetString("Σχολιο", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
